source 'https://rubygems.org'

gem 'jekyll', '2.5.3', :git => 'https://github.com/mattr-/jekyll.git', :branch => 'jekyll-4011'
gem 'jekyll-sitemap'
gem 'octopress', '~> 3.0'
gem 'kramdown'
gem 'coderay'
gem 'rake'
gem 'rack'
gem 'rack-jekyll'
gem 'thor'
gem 'activesupport'
gem 'stringex'
gem 'jekyll-feed'
ruby '2.2.3'
