source 'https://rubygems.org'

gem 'jekyll', '2.4.0'
gem 'jekyll-sitemap'
gem 'octopress', '~> 3.0'
gem 'kramdown'
gem 'coderay'
gem 'rake'
gem 'rack'
gem 'rack-jekyll'
gem 'thor'
gem 'activesupport'
gem 'stringex'
ruby '2.2.3'
